### PR TITLE
(MCOMPILER-358) Unable to compile project with module-info.java

### PR DESCRIPTION
**Pull request by rfscholte**
I've done a minimum of changes to make it compile and to make the tests succeed that rely on the module descriptor.
The project still has 3 failing tests: `java.lang.IllegalStateException: Unable to find a @SpringBootConfiguration, you need to use @ContextConfiguration or @SpringBootTest(classes=...) with your test`

### CODE REVIEW

**Review by jactor-rises — COMMENTED** [review]
your commit said: "...make module open"... where?

**Comment by rfscholte** [comment]
https://github.com/rfscholte/jactor-rises/blob/v1_1/jactor-applications/jactor-facade/src/main/java/module-info.java#L1

Spring requires open packages, not exported packages

**Comment by jactor-rises** [comment]
oh... I see... open the module...

I have 2 other spring-boot applications in my project without the need to open these modules... I do not want to open my entire module. Is it not possible to open a package in a module and specify which module which have access to this open package?

**Comment by rfscholte** [comment]
sure, you can say `open org.foo.package.name to some.module.name`. Just wanted to demonstrate that it is not a maven-plugin issue with the least amount of effort.

**Comment by jactor-rises** [comment]
Thank for the pointers... I am going to rewrite some code and possible remove `module-info.java`from the spring-boot applications.

Other pointers: https://stackoverflow.com/questions/51916421/how-to-create-a-modular-spring-boot-application-using-module-info-java?noredirect=1#comment90782913_51916421

**Pull request closed without merging**
